# Estructuras de datos: Listas



## Lista

La primera estructura de datos que veremos son las **listas**. Éstas son un conjunto de elementos ordenados separados por comas y escritos entre claudators, `[]`. 

Las listas son:
- hetereogéneas: los elementos pueden ser de distinto tipo en una misma lista
- mutables: los elementos pueden ser modificados

Un ejemplo de lista sería

In [ ]:
l = ["Juan", 31, 172.32, True]
print(l)

['Juan', 31, 172.32, True]


In [ ]:
type(l)

list

### Tamaño de una lista

Para saber la longitud o el tamaño de una lista, podemos hacer uso de la función `len()`

In [ ]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
len(l)

9

In [ ]:
l = ["Zoe", "Pablo", "Miguel", "Silvia"]
len(l)

4

### Elementos de una lista

Cada elemento en la lista tiene su propio índice

In [ ]:
names = ["Maria", "Juan", "Claudia", "Jorge", "Avelina"]

A `María` le corresponde el índice 0; a `Juan`, el 1; a `Claudia` el 2; a `Jorge`, el 3; y a `Avelina`, el 4.

**¡Cuidado!** En `Python`, los índices siempre empiezan en 0. De este modo, al primer elemento le corresponde el índice 0; al segundo, el índice 1; y al $n$-ésimo, le corresponde el índice $n−1$.

Dada una lista, podemos acceder a sus elementos utilizando la sintaxis `[]`.

In [ ]:
print(names[0])

Maria


In [ ]:
print(names[3])

Jorge


**¡Cuidado!** Si dada una lista llamamos a un elemento cuyo índice no existe para dicha lista, `Python` automáticamente nos devolverá error.

Podemos acceder a los últimos elementos de la lista haciendo uso de índices negativos.

In [ ]:
print(names[-1]) # Último elemento

Avelina


In [ ]:
print(names[-3]) # Tercer elemento empezando por el final

Claudia


Si en vez de querer acceder a los elementos uno por uno estamos interesados en acceder a avarios elementos a la vez, podemos hacer uso de la función `:`

In [ ]:
print(names[2:4])

['Claudia', 'Jorge']


In [ ]:
print(names[:3])

['Maria', 'Juan', 'Claudia']


In [ ]:
print(names[3:])

['Jorge', 'Avelina']


**Observación.** En cuanto a la función `:`

- El índice indicado a la derecha de los `:` nunca es incluido
- Si no indicamos elemento a la izquierda de los `:`, por defecto `Python` interpreta que se trata del 0
- Si no indicamos elemento a la derecha, por defecto `Python`interpreta que debe mostrar los elemetos desde el índice indicado a la izquierda hasta el último.

Además de acceder, podemos modificar los elementos de una lista

In [ ]:
names[0] = "Marina"
names[3] = "Jaime"
names

['Marina', 'Juan', 'Claudia', 'Jaime', 'Avelina']

Podemos añadir nuevos elementos a una lista con el método `.append()`

In [2]:
names = ["María", "Cristina", "Juana"]
print(names)

names.append("Andrea")
print(names)
names.append("Ana")
print(names)
names.append("Ana")
print(names)

['María', 'Cristina', 'Juana']
['María', 'Cristina', 'Juana', 'Andrea']
['María', 'Cristina', 'Juana', 'Andrea', 'Ana']
['María', 'Cristina', 'Juana', 'Andrea', 'Ana', 'Ana']


**Observación.** Los elementos añadidos con el método `.append()`, se incluyen al final.

Si quisiéramos añadir un nuevo elemento a una lista, pero no lo quisiéramos al final, sino en una posición específica, entonces utilizaremos el método `.insert()` al que primero le indicamos el índice donde queremos posicionar el nuevo elemento y, en segundo lugar, indicamos dicho nuevo elemento.

In [ ]:
names = ["Mario", "Cristian", "Juan"]
print(names)

names.insert(1, "Andrés")
print(names)
names.insert(3, "Miguel")
print(names)

['Mario', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Miguel', 'Juan']


**Observación.** Cuando le indicamos que queremos el elemento `Andrés` en el índice 1, el que antes ocupaba dicho índice, `Cristian`, pasa a ocupar el siguiente, 2, y así con el resto de elementos que van a continuación.

Ejercicios con María

Vamos a pedirle al usuario la longitud de una lista y haremos que introduzca por teclado tantos números enteros como haya indicado, que se guardarán en una lista. Al acabar. imprimiremos la lista.

In [ ]:
lista = []
n = int(input("Por favor, introduce el tamaño de la lista: "))

for i in range(0, n):
    lista.append(int(input("Indica el número: ")))

print("aquí tienes tu lista: ", lista)

Por favor, introduce el tamaño de la lista: 3
Indica el número: -3
Indica el número: 5
Indica el número: 9
aquí tienes tu lista:  [-3, 5, 9]


## Bucles con listas

Si quisiéramos imprimir por pantalla todos los elementos de una lista, lo podríamos hacer mediante los índices

In [ ]:
for i in range(len(names)): #Control sobre el indice
  print(names[i])

Mario
Andrés
Cristian
Miguel
Juan


o mucho más fácilmente iterando la lista con un `for` con la siguiente sintaxis:

In [ ]:
for name in names: #Forma más sencilla, pero desconocemos el indice
  print(name)

Mario
Andrés
Cristian
Miguel
Juan


## Concatenación de listas

Dadas dos o más listas, podemos concatenarlas haciendo uso de la función `+`

In [ ]:
l1 = [True, 21, "Marta"]
l2 = [22.5, False, 22, "Rafa"]
print(l1 + l2)

[True, 21, 'Marta', 22.5, False, 22, 'Rafa']


## Repetición de listas

Podemos repetir una misma lista tantas veces como queramos con la función `*`

In [ ]:
abc = ["A", "B", "C"]
print(abc * 5)

['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']


## Lista vacía

In [ ]:
empty_list = []
print(len(empty_list))

0


Ejercicio de prueba

Crear una lista con tres listas anidadas que a su vez contengan 5 números enteros


In [ ]:
workers = []
worker = [2] * 5
workers.append(worker * 3)
print(workers) 

lista = [["Jorge", "Martín", "Andrea"], 
         ["Esther", [1, 2, 3, 4, 5], 
         32], 
         2]
print(lista)

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
[['Jorge', 'Martín', 'Andrea'], ['Esther', [1, 2, 3, 4, 5], 32], 2]


## Más métodos de listas

El método `.count()` recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista

In [ ]:
numbers = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]

counted = []
for element in numbers:
  if element not in counted:
    counted.append(element)
    print("El elemento {} aparece {} veces".format(element, numbers.count(element)))

El elemento 0 aparece 1 veces
El elemento 1 aparece 2 veces
El elemento 2 aparece 3 veces
El elemento 3 aparece 4 veces


El método `.extend()` extiende la lista agregando al final el iterable indicado por parámetro.

In [ ]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.extend([6])
print(numbers)
numbers.extend([7, 8])
print(numbers)
numbers.extend(range(9, 16))
print(numbers)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


**Observación.** Un iterable es un objeto de `Python` capaz de devolver sus elementos uno por uno, permitiendo ser iterado en un bucle for. De momento solo conocemos las listas y el resultado de `range()`, pero en secciones futuras veremos los diccionarios, las tuplas y los conjuntos, que también son objetos iterables.

El método `index()` recibe un elemento como argumento y devuelve el índice de la primera aparición en la lista.

In [ ]:
numbers = [0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
print(numbers.index(2))
print(numbers.index(4)) 

3
7


El método `.pop()` devuelve el último elemento de la lista y lo borra de la misma.

In [ ]:
print(numbers)
for i in range(5):
    print(numbers.pop())#Devuelve el último elemnto de la lista y lo elimina
    print(numbers)

[0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3, 4, 3]
3
[0, 1, 1, 2, 2, 2, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3]
3
[0, 1, 1, 2, 2, 2]
2
[0, 1, 1, 2, 2]


El método `.remove()` recibe como argumento un elemento y borra su primera aparición de la lista.

In [ ]:
numbers = [0, 1, 2, 4, 3, 4, 5, 6, 7]
numbers.remove(4)#Borra la primera aparición del elemento indicado
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7]


El método `.reverse()` devuelve la lista en orden inverso.

In [ ]:
numbers = [1, -1, 2, -2, 3, -3]
numbers.reverse()
print(numbers)

[-3, 3, -2, 2, -1, 1]


El método `.sort()` devuelve la lista en orden. 

In [ ]:
numbers = [1, 3, 5, 2, 4]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


Si quisiésemos ordenar los elementos en orden decreciente, podríamos hacer uso del parámetro `reverse` del método `.sort()`:

In [ ]:
numbers = [1, 3, 5, 2, 4]
numbers.sort(reverse = True)
print(numbers)

[5, 4, 3, 2, 1]


Ejercicios con María

Dada una lista de caracteres, le pedimos al usuario qué elemento quiere eleiminar y lo eliminamos de la lista.

In [ ]:
l = ["s", "d", "f", "e","l"]
print("Esta es la lista original: ", l)
c = input("Que caracter quieres eliminar?: ")
c = c.lower()

for i in l:

    if i == c:
        l.remove(c)

print("Así queda la lista ahora: ", l)


Esta es la lista original:  ['s', 'd', 'f', 'e', 'l']
Que caracter quieres eliminar?: f
El caracter f no está en la lista
El caracter f no está en la lista
Así queda la lista ahora:  ['s', 'd', 'e', 'l']
El caracter f no está en la lista


Ejercicio con María

Vamos a pedir al usuario que ingrese 10 números, los guardamos en una lsita y mostraremos a la lista ordenada, sinedo el usuario quine indique l orden: ascendente o descendente.

In [ ]:
ndente

In [ ]:
rev = bool(input("Si quieres orden Descendente escribe cualquier letra o número, de lo contrario pulsa Enter para seguir"))

if rev:
    print("Descendente pues")
else:
    print("Ascendente pues")

print("Ingresa 10 números.")
l = []

for i in range(10):
    l.append(input("Ingresa el número {}: ".format(i + 1)))

l.sort(reverse = rev)
print("Esta es la lista: ", l)

Si quieres orden Descendente escribe 'True', de lo contrario pulsa Enter para seguirf
Ingresa 10 números.
Descendente pues
Ingresa el número 1: 1
Ingresa el número 2: 2
Ingresa el número 3: 3
Ingresa el número 4: 4
Ingresa el número 5: 5
Ingresa el número 6: 6
Ingresa el número 7: 7
Ingresa el número 8: 8
Ingresa el número 9: 9
Ingresa el número 10: 0
Esta es la lista:  ['9', '8', '7', '6', '5', '4', '3', '2', '1', '0']


**Observación.**  De momento solo conocemos las listas y el resultado de `range()`, pero en secciones futuras veremos los diccionarios, las tuplas y los conjuntos, que también son objetos iterables.

## Conversión a listas

Para convertir un objeto iterable de `Python` a lista, hay que usar la función `list()`

In [ ]:
print(range(0, 100, 10))

range(0, 100, 10)


In [ ]:
print(type(range(0, 100, 10)))

<class 'range'>


In [ ]:
print(list(range(0, 100, 10)))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
print(type(list(range(0, 100, 10))))

<class 'list'>


Ejericicios con María

Vamos a convertir los números impares del 0 al 30 a una lista y mostrar los elementos con el formato "El valor {} ocupa el índice {}"

## Listas anidadas

Las listas anidadas son listas dentro de listas. Es decir, las listas no solo pueden contener números, strings o datos booleanos, sino que también pueden contener otras listas.



---

#### Ejemplo 1

A continuación mostramos una lista anidada, pues consta de 3 elementos:

- 1 lista de 3 strings
- 1 lista heterogénea de 3 elementos que a su vez contiene una lista con 5 números
- 1 número

In [ ]:
l = [["María", "Santos", "Fernández"],
     ["Juan", [1, 2, 3, 4, 5], 32], 
     2]
print(l)

[['María', 'Santos', 'Fernández'], ['Juan', [1, 2, 3, 4, 5], 32], 2]


Para acceder a un elemento, necesitamos indicar su índice. Si un elemento está en una lista dentro de una lista dentro de una lista, en primer lugar indicamos el índice de la lista exterior dentro de `[]`; después, el índice de la siguiente lista más exterior también entre `[]`; y por último, el índice de la lista más interna, claramente también entre `[]`.

Accedamos al string `Fernández`y luego al número `5`.

In [ ]:
print(l[0][2]) # Fernández
print(l[1][1][4]) # 5

Fernández
5


In [ ]:
odd = list(range(1, 30, 2))

for i in range(len(odd)):
    print("El valor {} ocupa el índice {}".format(odd[i], i))

El valor 1 ocupa el índice 0
El valor 3 ocupa el índice 1
El valor 5 ocupa el índice 2
El valor 7 ocupa el índice 3
El valor 9 ocupa el índice 4
El valor 11 ocupa el índice 5
El valor 13 ocupa el índice 6
El valor 15 ocupa el índice 7
El valor 17 ocupa el índice 8
El valor 19 ocupa el índice 9
El valor 21 ocupa el índice 10
El valor 23 ocupa el índice 11
El valor 25 ocupa el índice 12
El valor 27 ocupa el índice 13
El valor 29 ocupa el índice 14


---



### Matrices

Hay un tipo muy utilizado de listas anidadas. Se caracteriza por ser una lista de $m$ listas, donde cada una de las listas tiene el mismo número de elementos, $n$. A este tipo de listas se les conoce como matrices.

In [ ]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

En matemáticas, las matrices se definen del siguiente modo.

**Matriz.** Una matriz de dimensiones $m\times n$ es una tabla formada por elementos dispuestos en $m$ filas y $n$ columnas de la forma

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{pmatrix}$$

Los elementos de la matriz se representan con doble subíndice, $a_{ij}$, donde el primero indica la fila a la que pertenece y, el segundo, la columna.

Entonces, la matriz que hemos definido anteriormente

In [ ]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

escrita en forma de tabla sería: `matrix` $= \displaystyle\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{pmatrix}$

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna

In [ ]:
matrix[0][2]

3

In [ ]:
matrix[1][1]

5

In [ ]:
matrix[2][0]

7

Podemos mostrar una matriz de `Python` en forma de tabla con un bucle `for`, del siguiente modo

In [ ]:
for row in matrix: # Accedemos a las filas de la matrix
  print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


Si lo que queremos es mostrar todos los elementos de la matriz en columna, podemos utilizar dos bucles `for` anidados del siguiente modo:

In [ ]:
for row in matrix: # Accedemos a las filas
  for element in row: # Accedemos a los elementos de las filas
    print(element)

1
2
3
4
5
6
7
8
9


Si lo que queremos es mostrar la matriz en forma de tabla, sin comas ni claudators por en medio, lo podemos hacer de dos formas:

- Haciendo uso de las dimensiones de la matriz y, por tanto, de la función `range()`
- Sin hacer uso de las dimensiones

La primera forma sería:

In [ ]:
# m es el número de filas y n, el de columnas
m = len(matrix)
n = len(matrix[0])

for i in range(m):
  for j in range(n):
    print(matrix[i][j], end = " ") #con el end=" " generamos una espacion en blanco en vez de un salto de linea
  print("")#Al colocar este print provocamos un salto a la linea siguiente

1 2 3 
4 5 6 
7 8 9 


**Observación.**

1. Como todas las filas tienen el mismo número de elementos, nos da igual si calculamos $n$ con la primera fila o con cualquier otra.
2. Hemos hecho uso del parámetro `end` de la función `print()` para indicar si, en vez de un salto de línea como ocurre por defecto, queremos que suceda otra cosa inmediatamente después de ejecutar la función `print()`. En este caso, hemos indicado que queremos un espacio en blanco.

Y la segunda forma, es la siguiente:

In [ ]:
for row in matrix:
  for element in row:
    print(element, end = " ")
  print("")

1 2 3 
4 5 6 
7 8 9 


#### Suma de matrices

Para poder sumar dos matrices, necesitamos que tengan la misma dimensión. Entonces, dadas $A$ y $B$ dos matrices con dimensión $m\times n$, su suma será una matriz de dimensión $m\times n$ y sus elementos se obtienen del siguiente modo:

$$\begin{array}{lll}A + B &=& (a_{ij})_{m\times n} + (b_{ij})_{m\times n} = (a_{ij} + b_{ij})_{m\times n}\\ 
&=&\begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} + \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1n}\\
b_{21} &b_{22} & \cdots &b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
b_{m1} &b_{m2} & \cdots & b_{mn}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\
\end{pmatrix}
\end{array}$$

Dadas dos matrices con la misma dimensión, las podemos usar haciendo uso de bucles `for` anidados.

In [ ]:
#Para sumar dos matrices, es necesario que estas tengan la misma dimensión
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

m = len(A)
n = len(A[0])

#Si coinciden el número de columnas y el número de filas...
if len(A) == len(B) and len(A[0]) == len(B[0]):
  C = [] #Se declara una lista vacía

  for i in range(m): #Bucle for para recorrer las filas
    C.append([]) #Se añade una lista vacía
    for j in range(n):#lee cada valor de cada fila (columnas)
      C[i].append(A[i][j] + B[i][j]) #Guarda la suma en la lista vacia

  print(C) #Se imprime

else:
  print("No se puede realizar la suma, pues las dimensiones de las matrices no coinciden.")

[[0, -2, -3], [0, 3, 1], [-1, -1, -3]]


El resultado de sumar las matrices $A$ y $B$ ha sido

$$\begin{pmatrix}
1 & 0 & -3\\
2 & 0 & 1\\
-1 & -1 & 0\end{pmatrix} + \begin{pmatrix}
-1 & -2 & 0\\
-2 & -3 & 0\\
0 & 0 & -3\end{pmatrix} = 
\begin{pmatrix}
0 & -2 & -3\\
0 & -3 & 1\\
-1 & -1 & -3\end{pmatrix}$$

In [ ]:
for row in C:
  print(row)

[0, -2, -3]
[0, 3, 1]
[-1, -1, -3]


**Observación.** Hemos puesto un `if` que, suponiendo que tanto $A$ como $B$ son matrices, comprueba si sus dimensiones coinciden. De ser cierto, procede a hacer la suma. De lo contrario, devuelve un mensaje indicando que la suma no puede llevarse a cabo.

#### Producto de matrices

Para poder multiplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo número de columnas que número de filas tiene la matriz de la derecha. Entonces, dadas las matrices $A$ y $B$ de dimensiones $m\times n$ y $n\times p$ respectivamente, su producto será una matriz de dimensión $m\times p$ y se obtiene del siguiente modo:

$$\begin{array}{lll}A\cdot B &=& (a_{ij})_{m\times n}\cdot (b_{ij})_{n\times p} = \left(\sum_{k = 1}^n a_{ik}\cdot b_{kj}\right)_{m\times p}\\
&=& \begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} \cdot \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1p}\\
b_{21} &b_{22} & \cdots &b_{2p}\\
\vdots & \vdots & \ddots & \vdots\\
b_{n1} &b_{n2} & \cdots & b_{np}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11}\cdot b_{11} + a_{12} \cdot b_{21} + \cdots + a_{1n}\cdot b_{n1} & \sum_{k = 1}^n a_{1k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{1k}\cdot b_{kp}\\
a_{21}\cdot b_{11} + a_{22} \cdot b_{21} + \cdots + a_{2n}\cdot b_{n1} & \sum_{k = 1}^n a_{2k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{2k}\cdot b_{kp}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1}\cdot b_{11} + a_{m2} \cdot b_{21} + \cdots + a_{mn}\cdot b_{n1} & \sum_{k = 1}^n a_{mk}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{mk}\cdot b_{kp}
\end{pmatrix}\end{array}$$

Dadas dos matrices, la primera con el mismo número de columnas que filas tiene la segunda, podemos multiplicarlas del siguiente modo:

In [ ]:
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]   #Matriz A
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]   #Matriz B

m, n, p = len(A), len(B), len(B[0]) #Número de filas de A, Número de Filas de B y Número de columnas de B

C = []  #Matriz producto vacía

for i in range(m):  #para cada fila de la primera
    C.append([])  #Crea una nueva fila vacía
    for j in range(p):    #para cada columna de la segunda matriz
        elemento = 0    #Define el elemento de la suma = 0
        for k in range(n):  #para cada columna de la primera y cada fila de la segunda
            elemento = elemento + A[i][k] * B[k][j]   #Al elemento se le suma a si mismo, más el producto de multiplicar elem.Fila * elem.Col
        C[i].append(elemento)   #Se añade elemento.Producto


[[1, 0, 7], [-1, -3, -4], [1, 2, 3]]


El resultado de multiplicar las matrices $A$ y $B$ ha sido

$$\begin{array}{lll} A\cdot B &=& 
\begin{pmatrix}
1 & 0 & -3 & 2\\
2 & 0 & 1 & 1\\
-1 & 0 & -1 & 0
\end{pmatrix}\cdot\begin{pmatrix}
-1 & -2 & 0\\
-2 & 3 & 0\\
0 & 0 & -3\\
1 & 1 & -1
\end{pmatrix}\\ &=& \begin{pmatrix}
1\cdot (-1) + 0\cdot (-2) -3\cdot 0 + 2\cdot 1 & 1\cdot (-2) + 0\cdot 3 -3\cdot 0 + 2\cdot 1 & 1\cdot 0 + 0\cdot 0 -3\cdot (-3) + 2\cdot (-1)\\
2\cdot (-1) + 0\cdot (-2) + 1\cdot 0 + 1\cdot 1  & 2\cdot (-2) + 0\cdot 3 + 1\cdot 0 + 1\cdot 1 & 2\cdot 0 + 0\cdot 0 + 1\cdot (-3) + 1\cdot (-1)\\
-1\cdot (-1) + 0\cdot (-2) -1\cdot 0 + 0\cdot 1  & -1\cdot (-2) + 0\cdot 3 -1\cdot 0 + 0\cdot 1 & -1\cdot 0 + 0\cdot 0 -1\cdot (-3) + 0\cdot (-1)
\end{pmatrix}\\ &=& \begin{pmatrix}
1 & 0 & 7\\
-1 & -3 & -4\\
1 & 2 & 3
\end{pmatrix}
\end{array}$$

In [ ]:
for row in C:
  print(row)

[1, 0, 7]
[-1, -3, -4]
[1, 2, 3]


Ejercicios con María

Vamos a crear manualmente una matriz de 4x4 y guardarla en una lista


In [ ]:
A = []

for i in range(4):
    A.append([])
    for j in range(4):
        A[i].append(float(input("Introduce el elemento ({}),({}): ".format(i, j))))

for i in range(4):
    for j in range(4):
        print(A[i][j], end = "  " if A[i][j] >= 0 else " ")
    print("")

Introduce el elemento (0),(0): 1
Introduce el elemento (0),(1): 2
Introduce el elemento (0),(2): 3
Introduce el elemento (0),(3): 4
Introduce el elemento (1),(0): 0
Introduce el elemento (1),(1): -1
Introduce el elemento (1),(2): 0
Introduce el elemento (1),(3): 1
Introduce el elemento (2),(0): -5
Introduce el elemento (2),(1): -6
Introduce el elemento (2),(2): -3
Introduce el elemento (2),(3): -2
Introduce el elemento (3),(0): 9
Introduce el elemento (3),(1): 7
Introduce el elemento (3),(2): 5
Introduce el elemento (3),(3): 3
1.0  2.0  3.0  4.0  
0.0  -1.0 0.0  1.0  
-5.0 -6.0 -3.0 -2.0 
9.0  7.0  5.0  3.0  


Ejercicios con María

Vamos a sumar dos matrices con lineas, Ambas matrices serán proporcionadas por el usuario, así como la dimensión de las matrices.

In [ ]:
n = int(input("Este es el número de filas de las matrices: "))
m = int(input("Este es el número de columnas de las matrices: "))

A = []
print("\n=== Matriz A ===")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}) ".format(i, j))))
  
B = []
print("\n=== Matriz B ===")
for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input("Introduce el elemento ({},{}) ".format(i, j))))

C = []
for i in range(n):
    C.append([])
    for j in range(m):
        C[i].append(A[i][j] + B[i][j])

print("\n=== Matriz A + B ===")
for i in range(n):
    for j in range(m):
        print(C[i][j], end = "  " if C[i][j] >= 0 else " ")
    print("")


Este es el número de filas de las matrices: 2
Este es el número de columnas de las matrices: 3

=== Matriz A ===
Introduce el elemento (0,0) 1
Introduce el elemento (0,1) 2
Introduce el elemento (0,2) 3
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) 2
Introduce el elemento (1,2) 1

=== Matriz B ===
Introduce el elemento (0,0) -1
Introduce el elemento (0,1) -1
Introduce el elemento (0,2) 0
Introduce el elemento (1,0) 1
Introduce el elemento (1,1) 0
Introduce el elemento (1,2) -1

=== Matriz A + B ===
0.0  1.0  3.0  
1.0  2.0  0.0  


Ejercicios con María

Vamos a calcular el producto de dos matrices con listas. Ambas matrices serán dadas por el usuario así como las dimensiones de ambas.

In [ ]:
n = int(input("Número de filas de la matriz A: "))
m = int(input("Número de columnas de la matriz A: ")) #Esta sirve para guardar número de columnas de A y número de filas de B, pues ambas deben coincidir
p = int(input("Número de columnas de la matriz B: "))

A = []
print("\n=== Matriz A ===")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}) ".format(i, j))))

B = []
print("\n=== Matriz B ===")
for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input("Introduce el elemento ({},{}) ".format(i, j))))

C = []
for i in range(n):
    C.append([])
    for j in range(p):
        elemento = 0
        for k in range(m):
            elemento += A[i][k] * B[k][j]
        C[i].append(elemento)

print("\n=== MAtriz A * B ===")

for i in range(n):
    for j in range(p):
        print(C[i][j], end = "  " if C[i][j] >= 0 else " ")
    print("")


Número de filas de la matriz A: 2
Número de columnas de la matriz A: 3
Número de columnas de la matriz B: 2

=== Matriz A ===
Introduce el elemento (0,0) 1
Introduce el elemento (0,1) 0
Introduce el elemento (0,2) 0
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) 1
Introduce el elemento (1,2) 0

=== Matriz B ===
Introduce el elemento (0,0) 3
Introduce el elemento (0,1) 2
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) 1
Introduce el elemento (2,0) -1
Introduce el elemento (2,1) 0

=== MAtriz A * B ===
3.0  2.0  
0.0  1.0  


#### Matrices con `numpy`

Existe una forma más sencilla de trabajar con matricdes y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

In [ ]:
import numpy as np #Libreria de trabajo numérico

Para crear una matriz vacía, usamos el método `.empty()`, al que le indicamos por parámetro las dimensiones

In [ ]:
A = np.empty((3, 3)) # 2 filas y 3 columnas
print(A)

[[4.67981378e-310 4.67981315e-310 4.67981378e-310]
 [0.00000000e+000 4.67981303e-310 1.58101007e-322]
 [4.94065646e-324 4.67981230e-310 4.94065646e-324]]


Para crear una matriz vacía con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.empty_like()`, al que le indicamos por parámetro la matriz existente

In [ ]:
B = np.empty_like(A) # Tendrá 2 filas y 3 columnas
print(B)

[[4.67981378e-310 4.67981315e-310 4.67981378e-310]
 [0.00000000e+000 4.67981303e-310 1.58101007e-322]
 [4.94065646e-324 4.67981230e-310 4.94065646e-324]]


Para crear una matriz nula, usamos el método `.zeros()`, al que le indicamos por parámetro las dimensiones

In [ ]:
C = np.zeros((3, 5)) # Matriz nula de dimensiones 3 x 5
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Para crear una matriz de ceros con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.zeros_like()`, al que le indicamos por parámetro la matriz existente

In [ ]:
D = np.zeros_like(A) # Tendrá 2 filas y 3 columnas y todos sus elementos valdrán 0
print(D)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz de unos, usamos el método `.ones()`, al que le indicamos por parámetro las dimensiones

In [ ]:
E = np.ones((1, 4)) # Matriz de unos de dimensiones 1 x 4
print(E)

[[1. 1. 1. 1.]]


Para crear una matriz de unos con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.ones_like()`, al que le indicamos por parámetro la matriz existente

In [ ]:
F = np.ones_like(C) # Tendrá 3 filas y 5 columnas y todos sus elementos valdrán 1
print(F)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [ ]:
M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
print(M)

[[ 1  0 -3  2]
 [ 2  0  1  1]
 [-1  0 -1  0]]


Para saber las dimensiones de una matriz, podemos utilizar el método `.shape`


In [ ]:
M.shape

(3, 4)

Ahora es más sencillo sumar matrices, pues solamente necesitamos la función `+`

In [ ]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrixSum = A + B
matrixSum

matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

También es más sencillo hacer el producto matricial $A\cdot B$ con el método `.dot()`

In [ ]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrixProd = A.dot(B)#Ojo que se multiplica con esto##############################################################
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

Gracias a `numpy`, también es mucho más sencillo mostrar una matriz en forma de tabla, pues nos basta con hacer uso de la función `print()`:

In [ ]:
print(matrixSum)
print(matrixProd)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]
[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]


En futuras secciones hablaremos más detenidamente de todo lo que es capaz la librería `numpy`.

Ejercicios con María

Vamos a introducir manualmente una matriz con numpy donde las dimensiones son introducidas por el usuario

In [ ]:
#import numpy as np
n = int(input("Número de filas de la matriz: "))
m = int(input("Número de columnas de la matriz: "))

A = np.empty((n, m))

for i in range(n):
    for j in range(m):
        A[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

print("\n=== Matriz A ===")
print(A)

Número de filas de la matriz: 3
Número de columnas de la matriz: 2
Introduce el elemento (0,0) 1
Introduce el elemento (0,1) 0
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) 2
Introduce el elemento (2,0) 1
Introduce el elemento (2,1) -1

=== Matriz A ===
[[ 1.  0.]
 [ 0.  2.]
 [ 1. -1.]]


Ejercicios con María

Camos a sumar dos matrices con numpy, ambas matrices las proporcionará el usuario, así como sus dimensiones


In [ ]:
#import numpy as np
n = int(input("Número de las filas: "))
m = int(input("Número de las columnas: "))

A = np.empty((n, m))
print("\n=== Matriz A ===")
for i in range(n):
    for j in range(m):
        A[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

B = np.empty((n, m))
print("\n=== Matriz B ===")
for i in range(n):
    for j in range(m):
        B[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

print("\n=== Matriz A + B ===")
print(A + B)



Número de las filas: 4
Número de las columnas: 2

=== Matriz A ===
Introduce el elemento (0,0) 1
Introduce el elemento (0,1) 0
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) -2
Introduce el elemento (2,0) 1
Introduce el elemento (2,1) -1
Introduce el elemento (3,0) 0
Introduce el elemento (3,1) 3

=== Matriz B ===
Introduce el elemento (0,0) 9
Introduce el elemento (0,1) 8
Introduce el elemento (1,0) 7
Introduce el elemento (1,1) 6
Introduce el elemento (2,0) 3
Introduce el elemento (2,1) 2
Introduce el elemento (3,0) 1
Introduce el elemento (3,1) 0

=== Matriz A + B ===
[[10.  8.]
 [ 7.  4.]
 [ 4.  1.]
 [ 1.  3.]]


Ejercicios con María

Camos a multiplicar dos matrices con numpy, ambas matrices las proporcionará el usuario, así como sus dimensiones

In [ ]:
#import numpy as np
n = int(input("Número de filas de A: "))
m = int(input("Número de columnas de A: "))
p = int(input("Número de columnas de A: "))

A = np.empty((n, m))
print("\n=== Matriz A ===")
for i in range(n):
    for j in range(m):
        A[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

B = np.empty((m, p))
print("\n=== Matriz B ===")
for i in range(m):
    for j in range(p):
        B[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

print ("\n===Matriz A * B ===")
print(A.dot(B))

Número de filas de A: 3
Número de columnas de A: 2
Número de columnas de A: 3

=== Matriz A ===
Introduce el elemento (0,0) 1
Introduce el elemento (0,1) 0
Introduce el elemento (1,0) 0
Introduce el elemento (1,1) 1
Introduce el elemento (2,0) 0
Introduce el elemento (2,1) 1

=== Matriz B ===
Introduce el elemento (0,0) 3
Introduce el elemento (0,1) 2
Introduce el elemento (0,2) 0
Introduce el elemento (1,0) 1
Introduce el elemento (1,1) 1
Introduce el elemento (1,2) -1

===Matriz A * B ===
[[ 3.  2.  0.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
