# La salida del templo

Entraron en la nueva sala y las puertas de piedra se cerraron tras ellos. Se giraron sobre sí mismos y observaron la gran y solitaria habitación en la que se encontraban.

Volvían a estar entre 4 paredes de piedra tan altas como las anteriores. Esta vez solo 2 de ellas tenían una ventana pequeña y cuadrada en lo más alto. La pared que quedaba tras ellos tenía solamente la gran puerta por la que habían entrado. Y en la pared opuesta podía verse otra puerta muy diferente a todas las anteriores.

Esta nueva puerta era un poco más pequeña y brillaba, pues era de oro macizo. Pero lo que más emocionó a Pyratilla y su tripulación fue que en letras grandes y brillantes ponía: SALIDA AL EXTERIOR. A punto estaban de correr hacia la puerta cuando en el centro de la habitación apareció un altar. Con cautela, los tres piratas se acercaron al altar.

El primero en llegar fue Pyratilla y en voz alta empezó a leer:

<dl>
<dd>"Esta es la prueba final:</dd>
<dd>al superarla al exterior podrás salir</dd>
<dd>un cuadrado perfecto vas a crear</dd>
<dd>y para ello las instrucciones debes seguir."</dd>
</dl>

Al pronunciar la última palabra, el texto del altar cambió mágicamente y ahora se leía:

<dl>
<dd>"INSTRUCCIONES:</dd>
<dd>Utiliza el módulo numpy</dd>
<dd>Dados los arrays a, b, c, d y e, concátenalos de modo que</dd>
<dd>* sea un array bidimensional</dd>
<dd>* su shape sea (5, 5)</dd>
<dd>* cada fila sume 65</dd>
<dd>* cada columna sume 65</dd>
<dd>* cada diagonal sume 65</dd>
<dd>PISTA: El número de la mala suerte ocupa el lugar central</dd>
<dd>Cuando lo hayas construido,</dd>
<dd>* comprueba la dimensión con el método correspondiente</dd>
<dd>* comprueba la shape con el método correspondiente</dd>
<dd>* comprueba que cada fila suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada columna suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada diagonal suma 65 con un método creado por ti</dd>
<dd>* con el método .ndenumerate() indica los índices de los elementos que son mayores a la media de los elementos del array bidimensional construido y los que no lo son</dd>
<dd>* muestra los elementos que sí han superado el filtro de ser mayores a la media de los elementos del array bidimensional construido"</dd>

</dl>


In [13]:
import numpy as np

In [14]:
a = np.array([[17, 5, 13, 21, 9]])
b = np.array([[23, 6, 19, 2, 15]])
c = np.array([[4, 12, 25, 8, 16]])
d = np.array([[11, 24, 7, 20, 3]])
e = np.array([[10, 18, 1, 14, 22]])

In [112]:
concat_arrays = np.concatenate((c, b, a, d, e), axis = 0)
print(concat_arrays)
print(concat_arrays.ndim)
print(concat_arrays.shape)
print("Las filas suman: ", np.sum(concat_arrays, axis = 1))
print("Las columnas suman: ", np.cumsum(concat_arrays, axis = 1))


for i in range(concat_arrays.ndim):
    print(np.sum(concat_arrays, axis = i))

[[ 4 12 25  8 16]
 [23  6 19  2 15]
 [17  5 13 21  9]
 [11 24  7 20  3]
 [10 18  1 14 22]]
2
(5, 5)
Las filas suman:  [65 65 65 65 65]
Las columnas suman:  [[ 4 16 41 49 65]
 [23 29 48 50 65]
 [17 22 35 56 65]
 [11 35 42 62 65]
 [10 28 29 43 65]]
[65 65 65 65 65]
[65 65 65 65 65]


In [91]:
concat_arrays.ndim

2

In [114]:
def diagonal_values(array):
    """
    Devuelve el valor de la suma de las diagonales de un array 2D
    Args:
        array (numpy.array): Array que se quiere evaluar
    Returns:
        (string): con los valores de cada diagonal
    """
    n = array.shape[0]
    sumR = 0
    sumL = 0
    for i in range(n):
        sumR += array[i][i]
        sumL += array[i][-1 -i]
    return "El valor de la diagonal de (0,0) a (1,-1) es de {}\ny el de la diagonal (1,0) a (0, -1) es de {}".format(sumR, sumL)

print(diagonal_values(concat_arrays))


El valor de la diagonal de (0,0) a (1,-1) es de 65
y el de la diagonal (1,0) a (0, -1) es de 65


In [118]:
half_values = sum(sum(concat_arrays)) / (concat_arrays.shape[0] * concat_arrays.shape[1])

list_upper_half_values_idx = []
list_lower_half_values_idx = []
print("===la media de los valores almacenados en la array es de {}===\n".format(half_values))
for n in np.ndenumerate(concat_arrays):
    if n[1] > half_values:
        list_upper_half_values_idx.append(n[0])
    else:
        list_lower_half_values_idx.append(n[0])

print("Lista de indices con valor superior a la media: \n", list_upper_half_values_idx)
print("Lista de indices con valor inferior a la media: \n", list_lower_half_values_idx)

list_upper_half_values = []
for n in np.ndenumerate(concat_arrays):
    if n[1] > half_values:
        list_upper_half_values.append(n[1])

values_profe = concat_arrays[concat_arrays > half_values]
print("valores como los saca el profesor: \n", values_profe)

print("Lista de indices con valor superior a la media: \n", list_upper_half_values)


===la media de los valores almacenados en la array es de 13.0===

Lista de indices con valor superior a la media: 
 [(0, 2), (0, 4), (1, 0), (1, 2), (1, 4), (2, 0), (2, 3), (3, 1), (3, 3), (4, 1), (4, 3), (4, 4)]
Lista de indices con valor inferior a la media: 
 [(0, 0), (0, 1), (0, 3), (1, 1), (1, 3), (2, 1), (2, 2), (2, 4), (3, 0), (3, 2), (3, 4), (4, 0), (4, 2)]
valores como los saca el profesor: 
 [25 16 23 19 15 17 21 24 20 18 14 22]
Lista de indices con valor superior a la media: 
 [25, 16, 23, 19, 15, 17, 21, 24, 20, 18, 14, 22]
