Ejercicio 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la
shape antes y después del reshape.

In [48]:
import numpy as np
print(np.__version__)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("\nArray a: \n", a)
print("Shape de array a: ", a.shape)

b = a.reshape(1, 3, 3)
print("\nArray b: \n", b)
print("Shape de array b: ", b.shape)

1.19.5

Array a: 
 [1 2 3 4 5 6 7 8 9]
Shape de array a:  (9,)

Array b: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape de array b:  (1, 3, 3)


Ejercicio 2

Dados los arrays 2D [[-6, -5], [-4, -3], [-2, -1]] y [[1, 2], [3, 4], [5, 6]], concaténalos de
modo que obtengas el array [[1, 2, -6, -5], [3, 4, -4, -3] [5, 6, -2, -1]].




In [ ]:
a = np.array([[-6, -5], [-4, -3], [-2, -1]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = np.concatenate((b, a), axis = 1)

print("Concatenación de a y b\n", c)

Concatenación de a y b
 [[ 1  2 -6 -5]
 [ 3  4 -4 -3]
 [ 5  6 -2 -1]]


Ejercicio 3

Dado el array 2D [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]], divídelo en 3 arrays 2D.


In [ ]:
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])

print("Array a original: \n", a)
d = np.array_split(a, 3)
n = 1
for i in d:
    print("Array a Dividido en {}/3: \n{}".format(n, i))
    n += 1

#Solución profesor
a1, a2, a3 = np.array_split(a, 3)


Array a original: 
 [[ 1  2  3]
 [-1  0  1]
 [ 4  5  6]
 [-4  0  4]
 [ 3  2  1]
 [-3  0  3]]
Array a Dividido en 1/3: 
[[ 1  2  3]
 [-1  0  1]]
Array a Dividido en 2/3: 
[[ 4  5  6]
 [-4  0  4]]
Array a Dividido en 3/3: 
[[ 3  2  1]
 [-3  0  3]]


Ejercicio 4

Dado el array 2D [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
"elle"]], busca las palabras que sean palíndromos.
PISTA: Necesitarás una función universal.


In [ ]:
def palindorme(array):
    """
    Devuelve las palabras palindromas pasadas por parametro en un array
    Args:
        array (numpy.array 2D)
    Returns:
        array (numpy.array) con los valores palíndormos
    """
    result = []
    for array_l2 in array:
        for word in array_l2:
            isPalindrome = False
            for i in range(len(word) // 2):
                if word[i] == word[-1 - i]:
                    isPalindrome = True
                else:
                    break
            if isPalindrome == True:
                result.append(word)

    return print(result)

a = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])

myPalindormeFunct = np.frompyfunc(palindorme, 1, 1)
palindorme(a)

['ala', 'kayak', 'elle']


Ejercicio 5

Dado el array 1D ["cena", "frío", "kayak", "remo", "sol"]], ¿qué índice deberá ocupar el elemento
“python” para que se mantenga el orden alfabético?


In [ ]:
a = np.array(["cena", "frío", "kayak", "remo", "sol"])
b = np.searchsorted(a, "python")
print(b)

3


Ejercicio 6

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número
del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!!
Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase
“¡Has fallado! ¡Prueba otra vez!”


In [49]:
from numpy import random as rd

In [ ]:
print("Intenta acertar en que número del 1 al 10 estoy pensando.")

num = 0
attempts = 0
while True:
    attempts += 1
    random_num = rd.randint(1, 10 + 1)
    num = int(input("Introduce un número: "))
    if num == random_num:
        break
    else:
        print("¡Has fallado! ¡Prueba otra vez!")

print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}".format(num))

s = "intento" 
if attempts != 1:
    s = "intentos"

print("Lo has conseguido en {} {}".format(attempts, s))

Intenta acertar en que número del 1 al 10 estoy pensando.
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un número: 5
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 5
Lo has conseguido en 15 intentos


Ejercicio 7

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros
entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá
que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El
1
juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente.
Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:
{}”

In [ ]:
a = rd.randint(1, 21, size= 5)

print(a)
print("Introduce 5 números del 1 al 20, a ver si averiguas en que 5 números enteros que estoy pensado y su posición")

while True:
    b = [int(input("número {}: ".format(1)))]
    for i in range(4):
        b = np.append(b, int(input("número {}: ".format(i + 2))))

    comparison = a == b
    hits = 0
    hits_position = []
    if comparison.all():
        break
    else:
        for idx, i in np.ndenumerate(b):
            hit = False
            for idy, j in np.ndenumerate(a):
                if hit == False and i == j :
                    hits += 1
                    hit = True
                if idx == idy and i == j:
                    hits_position.append(i)
                    break
        print("Has acertado {} números y los números {} están en su posición correcta".format(hits, hits_position))

print("¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}".format(a))

[11  2  7  4  3]
Introduce 5 números del 1 al 20, a ver si averiguas en que 5 números enteros que estoy pensado y su posición
número 1: 11
número 2: 2
número 3: 5
número 4: 1
número 5: 3
Has acertado 3 números y los números [11, 2, 3] están en su posición correcta
número 1: 112
número 2: 2
número 3: 7
número 4: 4
número 5: 3
Has acertado 4 números y los números [2, 7, 4, 3] están en su posición correcta
número 1: 11
número 2: 2
número 3: 7
número 4: 4
número 5: 3
¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: [11  2  7  4  3]


Ejercicio 8

A partir de la lista [-3, -2, -1, 0, 1, 2, 3], genera dos arrays aleatorios 2D de size = (3, 4) y
súmalos.


In [ ]:
a = np.array([-3, -2, -1, 0, 1, 2, 3])
b = rd.choice(a, size = (3, 4))
c = rd.choice(a, size = (3, 4))
print("\nArray original\n", a)
print("\nArray random 1\n", b)
print("\nArray random 2\n", c)


Array original
 [-3 -2 -1  0  1  2  3]

Array random 1
 [[ 2 -2  3  1]
 [-3 -3  0  0]
 [ 1 -1  0  1]]

Array random 2
 [[-2 -2  3 -1]
 [-2 -3 -2  2]
 [-1  0  3  1]]


Ejercicio 9

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.


In [ ]:
def total_vowels(array):
    """
    Devuelve el número total de vocales de cada string del array 
    pasado por parámetro.
    """
    a_str = np.array(array)
    result = 0
    for i in a_str.reshape(-1):
        for j in i:
            if j.lower() in ["a", "e", "i", "o", "u"]:
                result += 1
    
    return result


total_vowels = np.frompyfunc(total_vowels, 1, 1)

a = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])
print(total_vowels(a))

[[2 1 2]
 [2 2 2]
 [2 2 2]]


Ejercicio 10

Crea una función universal que dados un array 1D de valores string y conjunto de strings, compruebe para
cada elemento del array 1D, si está presente o no en el conjunto.


In [ ]:
def set_strings(array):
    set_standar = np.array(["ala", "delfín", "arroz", "cena", "kayak", "picnic", "hoja", "gato", "elle"])    

    yes = np.where(set_standar == array)
    if np.where(set_standar == array)[0] != None:
        return "La palabra {} si existe en el conjunto de stings".format(array)
    else:
        return "La palabra {} no existe en el conjunto de stings".format(array)

set_strings = np.frompyfunc(set_strings, 1, 1)

a = np.array(["programa", "ala", "agua", "kayak", "python", "gato"])
set_strings(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  """


array(['La palabra programa no existe en el conjunto de stings',
       'La palabra ala si existe en el conjunto de stings',
       'La palabra agua no existe en el conjunto de stings',
       'La palabra kayak si existe en el conjunto de stings',
       'La palabra python no existe en el conjunto de stings',
       'La palabra gato si existe en el conjunto de stings'], dtype=object)

In [ ]:
#solución del profesor
def is_in_set(element, s):
    """
    Devuleve si un elemento pertenece al conjunto
    Args:
        element: Elemento
        s: conjunto
    Returns:
        is_in: Boolean
    """
    if element in s:
        return True
    return False

np_is_in_set = np.frompyfunc(is_in_set, 2, 1)
np_is_in_set("koala", ["hola", "adios", "koala"])

array([False, False, True], dtype=object)

In [61]:
print(rd.rand(3))

[0.63319757 0.3501227  0.55326082]
