Ejercicio 1

Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
finalmente muestre la secuencia invertida.

In [4]:
#Se crea la lista de caracteres y la variable para almacenarlas
caracteres = "Estructuras de datos"
lista = []

#bucle que recorre el string
for caracter in caracteres:
    #Se agrega cada caracter leido a la lista
    lista.append(caracter)

#Se invierte la lista y se muestra
lista.reverse()
print(lista)

['s', 'o', 't', 'a', 'd', ' ', 'e', 'd', ' ', 's', 'a', 'r', 'u', 't', 'c', 'u', 'r', 't', 's', 'E']


Ejercicio 2

Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
mostrar el contenido de la lista.
Por ejemplo, si introducimos hola caracola y adios marieta, debería mostrarse haodleao sc
amraarcioeltaa.

In [7]:
#Se crean las listas de caracteres y la variable para almacenarlas
cadena1 = "Estructuras de datos"
cadena2 = "Las cadenas lo mejor"
fusion = []

#bucle que recorre los string
for c in range(len(cadena1)):
    #Se agrega el caracter correspondiente de cada string según el índice
    fusion.append(cadena1[c])
    fusion.append(cadena2[c])

#Se muestra
print(fusion)

['E', 'L', 's', 'a', 't', 's', 'r', ' ', 'u', 'c', 'c', 'a', 't', 'd', 'u', 'e', 'r', 'n', 'a', 'a', 's', 's', ' ', ' ', 'd', 'l', 'e', 'o', ' ', ' ', 'd', 'm', 'a', 'e', 't', 'j', 'o', 'o', 's', 'r']


Ejercicio 3

Crea un programa que lea un string y guarde en una lista todas las consonantes.

In [17]:
#Se crea la lista de caracteres y la variable para almacenarlas
caracteres = "Estructuras de datos"
consonantes = []

#Nos aseguramos de que las letras almacenadas estén en minúscula
caracteres = caracteres.lower()
for caracter in caracteres:
    #Si el caracter almacenado no es una vocal...
    if caracter != "a" and caracter != "e" and caracter != "i" and caracter != "o" and caracter != "u":
        #... se añade a la lista
        consonantes.append(caracter)

print(consonantes)

['s', 't', 'r', 'c', 't', 'r', 's', ' ', 'd', ' ', 'd', 't', 's']


Ejercicio 4

Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.

In [31]:
#Se pide al usuario que ingrese una palabra, por ejemplo ojo, y se declara una variable de lista y una boolean
word = input("Ingresa una palabra para averigüar si es palíndromo, puedes probar con 'ojo': ")
list_1 = []
palindrome = False

#Bucle que recorre la palabra
for letter in word:
    #Se añade cada letra a la lista
    list_1.append(letter)

#Se invierte la lista
list_1.reverse()
#Bucle que recorre los indices de la lista
for i in range(len(list_1)):
    #Se comparan las letras de la lista y la cadena...
    if list_1[i] == word[i]:
        #... si coinciden se pasa a true la variable
        palindrome = True
    else:
        #... si no coinciden se pasa la bool a False y se sale del bucle
        palindrome = False
        break

#Según si la palabra introducida es un palindromo se muestra una frase u otra
if palindrome:
    print("La palabra {} si es un palíndromo".format(word))
else:
    print("La palabra {} no es un palíndromo".format(word))



Ingresa una palabra para averigüar si es palíndromo: ojo
La palabra ojo si es un palíndromo


Ejercicio 5

Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

In [84]:
#Se crea la matriz y se le da valor a los elementos
matrix = [[1, 3, 31], [4, 8, 6], [7, 2, 1]]

#Bucle que recorre las filas
for i in range(len(matrix)):
    #Se crea un valor entero para comparar
    v = 0
    #Bucle que recorre los elementos de cada fila y los compara con el valor de v
    for j in range(len(matrix[i])):
        #Se compara el valor de v y se iguala al elemento si este último es mayor
        if matrix[i][j] > v:
            v = matrix[i][j]
    #Se devuelve la fila y el valor v como calor máximo de la fila
    print("El valor máximo de la fila {} es {}".format(matrix[i], v))

El valor máximo de la fila [1, 3, 31] es 31
El valor máximo de la fila [4, 8, 6] es 8
El valor máximo de la fila [7, 2, 1] es 7
3


Ejercicio 6

Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición
debe contener su orden en la matriz (desde 0 hasta n
2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz

[0, 1, 2]

[3, 4, 5]

[6, 7, 8]


In [58]:
#Pedimos el número y declaramos la lista y un entero con valor 0
n = int(input("introduce un número entero: "))
matrix = ([])
v = 0

#Bucle que crea las líneas
for i in range(n):
    matrix.append([])
    #Bucle que crea las columnas
    for j in range(n):
        #Se da al nuevo objeto un valor v y este último se incrementa
        matrix[i].append(v)
        v += 1
    #Se imprime cada columna
    print(matrix[i])
    

introduce un número entero: 3
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


Ejercicio 7

Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada
columna es el mismo valor.


In [66]:
#Se crean dos matrices, una para cargar los valores y otra para guardar las sumas de las columnas
A = []
B = []

#Bucle que crea cada fila
for i in range(3):
    A.append([])
    #Bucle que pide al usuario la inserción del valor para elemento
    for j in range(3):
        A[i].append(int(input("Introduce el elemento ({}),({}): ".format(i, j))))

#Bucle que crea cada fila y recorre las de la matriz A
for i in range(len(A)):
    B.append([])
    B[i] = 0 #Se le da un valor al elemento
    #Matriz que suma los elementos de cada fila y los guarda en B
    for j in range(len(A[i])):
        B[i] += A[i][j]

#Se compara el resultado almacenado en cada fila de B con las otrs dos y se da una respuesta
if B[0] == B[1] and B[0] == B[2] and B[1] == B[2]:
    print("Las columnas de la matriz tienen el mismo valor")
else: 
    print("Las columnas de la matriz tienen distinto valor")

Introduce el elemento (0),(0): 1
Introduce el elemento (0),(1): 2
Introduce el elemento (0),(2): 3
Introduce el elemento (1),(0): 2
Introduce el elemento (1),(1): 2
Introduce el elemento (1),(2): 2
Introduce el elemento (2),(0): 4
Introduce el elemento (2),(1): 1
Introduce el elemento (2),(2): 1
Las columnas de la matriz tienen el mismo valor


Ejercicio 8

Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos) se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

In [69]:
#Se pide la cantidad de filas y solumnas que se desean y se declara la matriz vacía
n = int(input("Número de filas de la matriz A: "))
m = int(input("Número de columnas de la matriz A: ")) 
A = []

#Bucle que crea las filas
for i in range(n):
    A.append([])
    #Bucle que crea los elementos
    for j in range(m):
        A[i].append([])

#Se compara la cantidad de filas con la cantidad de elementos de cada una (columnas)
if len(A) == len(A[0]):
    print("La matriz si es una matriz 'Identidad'")
else:
    print("La matriz no es una matriz 'Identidad'")

Número de filas de la matriz A: 3
Número de columnas de la matriz A: 4

=== Matriz A ===
La matriz no es una matriz 'Identidad'


Ejercicio 9

Realiza un programa que calcule la matriz transpuesta.

In [77]:
#Se crea la matriz identidad y una matriz vacía
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A2 = []

#Bucle que crea y recorre las filas
for i in range(len(A)):
    A2.append([])
    #Bucle que crea y recorre los elementos
    for j in range(len(A[i])):
        #Se usa el indice j para leer el valor i de cada fila
        A2[i].append(A[j][i])

#Se muestra la matriz identidad
print("\n=== Matriz A ===")
for row in A:
    print(row)
#Se muestra la matriz traspuesta
print("\n=== Matriz traspuesta de A ===")
for row in A2:
    print(row)


=== Matriz A ===
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

=== Matriz traspuesta de A ===
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


Ejercicio 10

Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
numpy.

In [83]:
#Se importa la libreria numpy y crea un boolean para controlar un bucle
import numpy as np
ok = False

#mietras no se inserte una matriz identidad
while ok == False:
    #Se le pide al usuario que introduzca las dimensiones
    n = int(input("Número de filas de A: "))
    m = int(input("Número de columnas de A: "))
    #Se crea un entero para almacenar valores
    v = 0

    #Se pide a numpy que cree la matriz
    A = np.empty((n, m))

    #Se compara la cantidad de filas con la cantidad de elementos de cada una (columnas)
    #para conocer si es una matriz identidad
    if len(A) == len(A[0]):
        #Bucle que recorre las fiasl
        for i in range(n):
            #Bucle que recorre los elementos y les asigna el valor de v incrementado este despues
            for j in range(m):
                A[i, j] = v
                v += 1
                
        #Se muestra la matriz identidad
        print("\n=== Matriz A ===")
        for row in A:
            print(row)
        ok = True  
    else:
        print("La matriz no es una matriz 'Identidad', prueba de nuevo")

Número de filas de A: 3
Número de columnas de A: 4
La matriz no es una matriz 'Identidad', prueba de nuevo
Número de filas de A: 3
Número de columnas de A: 3

=== Matriz A ===
[0. 1. 2.]
[3. 4. 5.]
[6. 7. 8.]
